/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\zhangtianqi\\Desktop\\doc\\node_modules\\_@vuepress_core@1.8.2@@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-76612d88",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-76612d88").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-96537982",
    path: "/pages/vue/diff.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-96537982").then(next)
    },
  },
  {
    name: "v-304e943e",
    path: "/pages/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-304e943e").then(next)
    },
  },
  {
    path: "/pages/vue/index.html",
    redirect: "/pages/vue/"
  },
  {
    name: "v-4444f85e",
    path: "/pages/react/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4444f85e").then(next)
    },
  },
  {
    path: "/pages/react/index.html",
    redirect: "/pages/react/"
  },
  {
    name: "v-0b521725",
    path: "/pages/vue/react.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0b521725").then(next)
    },
  },
  {
    name: "v-1ccae16e",
    path: "/pages/JavaScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ccae16e").then(next)
    },
  },
  {
    path: "/pages/JavaScript/index.html",
    redirect: "/pages/JavaScript/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]