/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "ztq",
  "description": "ztq",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/tiance.png"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/tiance.png",
        "heroText": "砥砺前行",
        "tagline": "挫折不过是人生路途中的些许风霜",
        "actionText": "开始007",
        "actionLink": "/pages/index/index.md",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-76612d88",
      "path": "/",
      "createdTime": 1635410282000
    },
    {
      "title": "vue",
      "frontmatter": {},
      "regularPath": "/pages/vue/diff.html",
      "relativePath": "pages/vue/diff.md",
      "key": "v-96537982",
      "path": "/pages/vue/diff.html",
      "headers": [
        {
          "level": 2,
          "title": "vue",
          "slug": "vue"
        }
      ],
      "createdTime": 1635410282000
    },
    {
      "title": "vue",
      "frontmatter": {},
      "regularPath": "/pages/vue/",
      "relativePath": "pages/vue/index.md",
      "key": "v-304e943e",
      "path": "/pages/vue/",
      "headers": [
        {
          "level": 2,
          "title": "vue",
          "slug": "vue"
        }
      ],
      "createdTime": 1635410282000
    },
    {
      "title": "vue",
      "frontmatter": {},
      "regularPath": "/pages/react/",
      "relativePath": "pages/react/index.md",
      "key": "v-4444f85e",
      "path": "/pages/react/",
      "headers": [
        {
          "level": 2,
          "title": "vue",
          "slug": "vue"
        }
      ],
      "createdTime": 1635410282000
    },
    {
      "title": "vue",
      "frontmatter": {},
      "regularPath": "/pages/vue/react.html",
      "relativePath": "pages/vue/react.md",
      "key": "v-0b521725",
      "path": "/pages/vue/react.html",
      "headers": [
        {
          "level": 2,
          "title": "vue",
          "slug": "vue"
        }
      ],
      "createdTime": 1635410282000
    },
    {
      "title": "JavaScript 篇",
      "frontmatter": {},
      "regularPath": "/pages/JavaScript/",
      "relativePath": "pages/JavaScript/index.md",
      "key": "v-1ccae16e",
      "path": "/pages/JavaScript/",
      "headers": [
        {
          "level": 2,
          "title": "JavaScript 篇",
          "slug": "javascript-篇"
        },
        {
          "level": 3,
          "title": "JavaScript 有⼏种类型的值",
          "slug": "javascript-有几种类型的值"
        },
        {
          "level": 3,
          "title": "JavaScript 中的 Symbol 是什么？",
          "slug": "javascript-中的-symbol-是什么"
        },
        {
          "level": 3,
          "title": "介绍 JavaScript 有哪些内置对象",
          "slug": "介绍-javascript-有哪些内置对象"
        },
        {
          "level": 3,
          "title": "null，undefined 的区别",
          "slug": "null-undefined-的区别"
        },
        {
          "level": 3,
          "title": "判断数据类型￥",
          "slug": "判断数据类型¥"
        },
        {
          "level": 3,
          "title": "数据类型转换",
          "slug": "数据类型转换"
        },
        {
          "level": 3,
          "title": "用到的 String 方法",
          "slug": "用到的-string-方法"
        },
        {
          "level": 3,
          "title": "统计出现次数最多的字符串，及其最大值和最大值对应的字符串",
          "slug": "统计出现次数最多的字符串-及其最大值和最大值对应的字符串"
        },
        {
          "level": 3,
          "title": "遍历对象属性￥",
          "slug": "遍历对象属性¥"
        },
        {
          "level": 3,
          "title": "js 判断数组中是否包含某个元素",
          "slug": "js-判断数组中是否包含某个元素"
        },
        {
          "level": 3,
          "title": "JS 判断对象是否为空对象的几种方法",
          "slug": "js-判断对象是否为空对象的几种方法"
        },
        {
          "level": 3,
          "title": "数组用到的方法￥",
          "slug": "数组用到的方法¥"
        },
        {
          "level": 3,
          "title": "如何通过 JS 判断⼀个数组",
          "slug": "如何通过-js-判断一个数组"
        },
        {
          "level": 3,
          "title": "JS 数组和对象的遍历⽅式，以及⼏种⽅式的⽐较",
          "slug": "js-数组和对象的遍历方式-以及几种方式的比较"
        },
        {
          "level": 3,
          "title": "数组去重⽅法总结",
          "slug": "数组去重方法总结"
        },
        {
          "level": 3,
          "title": "JavaScript 循环大总结， for, forEach，for in，for of, map 区别",
          "slug": "javascript-循环大总结-for-foreach-for-in-for-of-map-区别"
        },
        {
          "level": 3,
          "title": "es6 新特性￥￥￥￥￥￥",
          "slug": "es6-新特性¥¥¥¥¥¥"
        },
        {
          "level": 3,
          "title": "高阶函数和回调函数？",
          "slug": "高阶函数和回调函数"
        },
        {
          "level": 3,
          "title": "引入 js 文件，在 body 里和 head 区别？在 head 里引入 js 文件能获取 DOM 吗？不能的话，我想在 head 里获取到 DOM 怎么做？",
          "slug": "引入-js-文件-在-body-里和-head-区别-在-head-里引入-js-文件能获取-dom-吗-不能的话-我想在-head-里获取到-dom-怎么做"
        },
        {
          "level": 3,
          "title": "什么是事件代理",
          "slug": "什么是事件代理"
        },
        {
          "level": 3,
          "title": "script 标签中 defer 和 async 的区别",
          "slug": "script-标签中-defer-和-async-的区别"
        },
        {
          "level": 3,
          "title": "什么是⾯向对象编程和⾯向过程编程",
          "slug": "什么是面向对象编程和面向过程编程"
        },
        {
          "level": 3,
          "title": "⾯向对象编程思想",
          "slug": "面向对象编程思想"
        },
        {
          "level": 3,
          "title": "执行上下文",
          "slug": "执行上下文"
        },
        {
          "level": 3,
          "title": "闭包原理及结合项目优缺点￥￥￥￥￥￥",
          "slug": "闭包原理及结合项目优缺点¥¥¥¥¥¥"
        },
        {
          "level": 3,
          "title": "闭包",
          "slug": "闭包"
        },
        {
          "level": 3,
          "title": "原型原型链",
          "slug": "原型原型链"
        },
        {
          "level": 3,
          "title": "继承的方式",
          "slug": "继承的方式"
        },
        {
          "level": 3,
          "title": "继承",
          "slug": "继承"
        },
        {
          "level": 3,
          "title": "谈谈 This 对象的理解",
          "slug": "谈谈-this-对象的理解"
        },
        {
          "level": 3,
          "title": "call apply bind",
          "slug": "call-apply-bind"
        },
        {
          "level": 3,
          "title": "new 一个构造函数发生了什么",
          "slug": "new-一个构造函数发生了什么"
        },
        {
          "level": 3,
          "title": "垃圾回收机制￥",
          "slug": "垃圾回收机制¥"
        },
        {
          "level": 3,
          "title": "计数回收",
          "slug": "计数回收"
        },
        {
          "level": 3,
          "title": "内存溢出 内存泄漏",
          "slug": "内存溢出-内存泄漏"
        },
        {
          "level": 3,
          "title": "Ajax 原理",
          "slug": "ajax-原理"
        },
        {
          "level": 3,
          "title": "跨域方式",
          "slug": "跨域方式"
        },
        {
          "level": 3,
          "title": "eventloop ￥",
          "slug": "eventloop-¥"
        },
        {
          "level": 3,
          "title": "说一下 promise ￥￥",
          "slug": "说一下-promise-¥¥"
        },
        {
          "level": 3,
          "title": "async await 及内部实现￥￥",
          "slug": "async-await-及内部实现¥¥"
        },
        {
          "level": 3,
          "title": "谈谈你对 AMD、CMD 的理解",
          "slug": "谈谈你对-amd、cmd-的理解"
        },
        {
          "level": 3,
          "title": "eval 是做什么的",
          "slug": "eval-是做什么的"
        },
        {
          "level": 3,
          "title": "javascript 代码中的\"use strict\";是什么意思",
          "slug": "javascript-代码中的-use-strict-是什么意思"
        },
        {
          "level": 3,
          "title": "深浅拷贝￥￥￥",
          "slug": "深浅拷贝¥¥¥"
        },
        {
          "level": 3,
          "title": "节流防抖￥￥￥",
          "slug": "节流防抖¥¥¥"
        },
        {
          "level": 3,
          "title": "怎么判断两个对象相等？",
          "slug": "怎么判断两个对象相等"
        },
        {
          "level": 3,
          "title": "⽤过哪些设计模式？",
          "slug": "用过哪些设计模式"
        },
        {
          "level": 3,
          "title": "JS 的四种设计模式",
          "slug": "js-的四种设计模式"
        },
        {
          "level": 3,
          "title": "十七、柯里化",
          "slug": "十七、柯里化"
        },
        {
          "level": 3,
          "title": "编译器和解析器：V8 如何执行一段 JavaScript 代码的",
          "slug": "编译器和解析器-v8-如何执行一段-javascript-代码的"
        },
        {
          "level": 2,
          "title": "Web 相关篇",
          "slug": "web-相关篇"
        },
        {
          "level": 3,
          "title": "9. 常⻅ web 安全及防护原理",
          "slug": "_9-常⻅-web-安全及防护原理"
        },
        {
          "level": 3,
          "title": "10. WebSocket",
          "slug": "_10-websocket"
        },
        {
          "level": 3,
          "title": "11. ajax、axios、fetch 区别 jQuery ajax",
          "slug": "_11-ajax、axios、fetch-区别-jquery-ajax"
        },
        {
          "level": 3,
          "title": "12. 项⽬做过哪些性能优化？",
          "slug": "_12-项目做过哪些性能优化"
        },
        {
          "level": 3,
          "title": "13. 负载均衡",
          "slug": "_13-负载均衡"
        },
        {
          "level": 3,
          "title": "14. CDN",
          "slug": "_14-cdn"
        },
        {
          "level": 3,
          "title": "15. babel 原理",
          "slug": "_15-babel-原理"
        }
      ],
      "createdTime": 1635411311000
    }
  ],
  "themeConfig": {
    "logo": "/tiance.png",
    "nav": [
      {
        "text": "vue",
        "link": "/pages/vue/index.md"
      },
      {
        "text": "react",
        "link": "/pages/react/index.md"
      },
      {
        "text": "JavaScript",
        "link": "/pages/JavaScript/index.md"
      },
      {
        "text": "Github",
        "link": "https://github.com/chai618"
      }
    ]
  }
}