/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "此木雨辰",
  "description": "万物生而有翼，你因何匍匐形同蝼蚁",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/tiance.png"
      }
    ]
  ],
  "pages": [
    {
      "title": "vue",
      "frontmatter": {},
      "regularPath": "/pages/flutter/",
      "relativePath": "pages/flutter/index.md",
      "key": "v-72ef0c49",
      "path": "/pages/flutter/",
      "headers": [
        {
          "level": 2,
          "title": "vue",
          "slug": "vue"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/tiance.png",
        "heroText": "砥砺前行",
        "tagline": "挫折不过是人生路途中的些许风霜",
        "actionText": "开始007",
        "actionLink": "/pages/index/index.md",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-0f5d5851",
      "path": "/"
    },
    {
      "title": "vue",
      "frontmatter": {},
      "regularPath": "/pages/react/",
      "relativePath": "pages/react/index.md",
      "key": "v-e8ca3cae",
      "path": "/pages/react/",
      "headers": [
        {
          "level": 2,
          "title": "vue",
          "slug": "vue"
        }
      ]
    },
    {
      "title": "vue",
      "frontmatter": {},
      "regularPath": "/pages/vue/diff.html",
      "relativePath": "pages/vue/diff.md",
      "key": "v-21308f0a",
      "path": "/pages/vue/diff.html",
      "headers": [
        {
          "level": 2,
          "title": "vue",
          "slug": "vue"
        }
      ]
    },
    {
      "title": "vue",
      "frontmatter": {},
      "regularPath": "/pages/vue/",
      "relativePath": "pages/vue/index.md",
      "key": "v-5fea49ee",
      "path": "/pages/vue/",
      "headers": [
        {
          "level": 2,
          "title": "vue",
          "slug": "vue"
        }
      ]
    },
    {
      "title": "vue",
      "frontmatter": {},
      "regularPath": "/pages/vue/react.html",
      "relativePath": "pages/vue/react.md",
      "key": "v-6b6ec7a0",
      "path": "/pages/vue/react.html",
      "headers": [
        {
          "level": 2,
          "title": "vue",
          "slug": "vue"
        }
      ]
    }
  ],
  "themeConfig": {
    "logo": "/tiance.png",
    "nav": [
      {
        "text": "vue",
        "link": "/pages/vue/index.md"
      },
      {
        "text": "react",
        "link": "/pages/react/index.md"
      },
      {
        "text": "flutter",
        "link": "/pages/flutter/index.md"
      },
      {
        "text": "Github",
        "link": "https://github.com/chai618"
      }
    ],
    "sidebar": {
      "/pages/vue/": [
        {
          "title": "原理",
          "collapsable": true,
          "sidebarDepth": 1,
          "children": [
            [
              "diff.md",
              "diff"
            ],
            [
              "react.md",
              "react"
            ]
          ]
        }
      ]
    }
  }
}